modLoader="javafml"
loaderVersion="[40,)"
license="Not specified"

[[mods]]
modId="fenceexample"
version="1.0.0"
displayName="fence example"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kiera, MCreator"

[[dependencies.fenceexample]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




